// Generated by CoffeeScript 1.10.0
var Person, Student,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Person = (function() {
  function Person(age, name) {
    this.age = age;
    this.name = name;
  }

  Person.prototype.introduce = function() {
    return "My name is " + this.name + ". I am " + this.age + " years old.";
  };

  return Person;

})();

Student = (function(superClass) {
  extend(Student, superClass);

  function Student(age, name, my_class) {
    Student.__super__.constructor.call(this, age, name);
    this["class"] = my_class;
  }

  Student.prototype.introduce = function() {
    return "I am a Student. I am at Class " + this["class"] + ".";
  };

  return Student;

})(Person);

//# sourceMappingURL=main.js.map
