// Generated by CoffeeScript 1.10.0
var Person;

Person = (function() {
  function Person(age, name) {
    this.age = age;
    this.name = name;
  }

  Person.prototype.introduce = function() {
    return "My name is " + this.name + ". I am " + this.age + " years old.";
  };

  return Person;

})();

//# sourceMappingURL=main.js.map
